### ISSUE TITLE
Passing data between jobs

### ISSUE THREAD

**Issue by jlugao** [jlugao/sauron-rule-engine#28]
We should have a global context available to all jobs so we can pass data between them. 

A further (and alternative) development would be using function arguments and returning the data to pass it to the next job. I don't like this idea as we will start to have too much magic going on.

@jfunez what do you think?

**Comment by jfunez** [comment]
yes, agree with less magic approach! 
based on good practices of Airflow, my suggestion is that data channel should be:
- easy to use
- optional to use
- separated from any control flow
- scoped only into the same execution flow

so each function/task/job can push and pull data between tasks that belong to the same flow.

1. task A: after get some results, push data to the data channel (`push key='foo' value='bar' `) this pair key value is related to the task id. Allowing other tasks to push the same key without overriding.
2. task B: don't read the data channel
3. task C: start reading data from the data channel to proceed with some processing (`pull from='task A', key='foo'` will return value `"bar"`)

**Comment by jlugao** [comment]
Currently we have to pass session on each and every function, is there a way to bypass this? or even, should we?

**Comment by jfunez** [comment]
it's very usefull for ETL case, at least.
and should apply for other use cases.
another approach could be having a global scope storage (i.e.: a database, or in memory dict) where the key is the name of callable that push info, and then other callables can retrieve data from there using the proper key

```python
global_session = Session()  
# Session class should have locks, to avoid problems with concurrency and paralelism
# Session class should have methods to push and pull that knows who is calling and add it as a key during each engine session 

def task_func_pusher(x, y):
   ...
   global_session.push('value_x', x)
   global_session.push('value_y', y)

def task_func_pull_x():
   ...
   pushed_x = global_session.pull(task_id='task_func_pusher', key='x')
   # here you use `pushed_x`

def task_func_pull_y():
   ...
   pushed_y = global_session.pull(task_id='task_func_pusher', key='y')
   # here you use `pushed_y`
```
of course pusher func should ran earlier than pull_x and pull_y

**Comment by jlugao** [comment]
I think that we should stick to the current engine-local session we have now. If we see the need we can reopen this
